let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
    silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

function! RunCtags()
    ! ctags --recurse .
endfunction

" let g:polyglot_disabled = ['autoindent']
" let g:polyglot_disabled = ['sensible']
" autocmd BufEnter * set indentexpr=
syntax on
set nocompatible

call plug#begin()
    " Plug 'eemed/sitruuna.vim'
    Plug 'Badacadabra/vim-archery'
    Plug 'jpo/vim-railscasts-theme'
    Plug 'vim-scripts/ansi_blows.vim'
    Plug 'w0ng/vim-hybrid'
    Plug 'nelstrom/vim-mac-classic-theme'
    Plug 'caglartoklu/borlandp.vim'
    Plug 'lycuid/far.vim'

    Plug 'Garzzza7/sitruuna_backup'
    Plug 'bfrg/vim-cpp-modern'
    Plug 'christophermca/meta5'
    Plug 'drsooch/gruber-darker-vim'
    Plug 'jfsicilia/Bclose'
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'junegunn/fzf.vim'
    Plug 'lifepillar/vim-solarized8'
    Plug 'ludovicchabant/vim-gutentags'
    Plug 'mbbill/undotree'
    Plug 'mhinz/vim-grepper'
    Plug 'overvale/vacme'
    Plug 'tpope/vim-commentary'
    Plug 'tpope/vim-dispatch'
    Plug 'tpope/vim-eunuch'
    Plug 'tpope/vim-fugitive'
    Plug 'tpope/vim-rhubarb'
    Plug 'tpope/vim-surround'
    Plug 'tpope/vim-vinegar'
    Plug 'vim-scripts/Tango-colour-scheme'
    Plug 'wezm/vim-mercury'

call plug#end()
packadd cfilter

let g:fzf_vim = {}
let g:fzf_vim.buffers_options = '--no-header --info default'

set laststatus=2
set statusline=
set statusline +=%f
set statusline +=%1*%=%5l%*
set statusline +=%2*/%L%*

set ttimeout
set ttimeoutlen=10
set scrolloff=8
set mouse=a
set autoread

set noswapfile

set rtp^="$HOME/.opam/default/share/ocp-indent/vim"

set wildmenu
set wildmode=full
set wildoptions=pum

set ignorecase

let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

set nocursorcolumn
set nocursorline
syntax sync minlines=256
let g:netrw_liststyle=3
" colo default
" colo railscasts
colo solarized8_high
" set background=dark
set background=dark
set hlsearch
set is hls
set incsearch

filetype plugin indent on

vnoremap J :m '>+1<cr>gv=gv
vnoremap K :m '<-2<cr>gv=gv

nnoremap            <C-s><C-d>      :GrepperGrep <C-r><C-w>
nnoremap            <C-s><C-a>      :%s/<C-r><C-w>//g<Left><Left>
nnoremap            <C-s><C-s>      :%s/<C-r><C-w>//gc<Left><Left><Left>
vnoremap            <C-s><C-s>      "ay:%s/<C-r>a//gc<Left><Left><Left>
nnoremap            <UP>            <cmd>echo "xdd"<cr>
nnoremap            <DOWN>          <cmd>echo "xdd"<cr>
nnoremap            <RIGHT>         <cmd>echo "xdd"<cr>
nnoremap            <LEFT>          <cmd>echo "xdd"<cr>
nnoremap            <A-C-w>         <cmd>wa<cr>
nnoremap            <A-C-q>         <cmd>qa!<cr>
nnoremap            <C-r>           <cmd>source $HOME/.vimrc<cr>
tnoremap            <Esc>           <C-\><C-n>
nnoremap            <A-n>           :bn<cr>
nnoremap            <ESC>n          :bn<cr>
nnoremap            <A-d>           :Bclose<CR>
" it is set for the sake of st
nnoremap            <Esc>d          :Bclose<CR>
noremap             <A-p>           :bp<cr>
noremap             <A-w>           :bw<cr>
noremap             <ESC>p          :bp<cr>
noremap             <ESC>w          :bw<cr>
noremap             <Esc><Esc>      :nohlsearch<CR>
noremap             <A><A>          :nohlsearch<CR>
noremap             <F8>            <esc>:w<cr> :Dispatch comp.sh $(echo %)<cr>
noremap             <F9>            <esc>:w<cr> :!python3<cr>
noremap             <F10>           <esc>:w<cr> :Dispatch! comp.sh $(echo %)<cr>
noremap             <space>sf      :FZF<cr>
noremap             <space>sa      :RG<cr>
noremap             <space><space> :Buffers<cr>
noremap             <space>/       :BLines<cr>
noremap             <space>ss      :Lines<cr>
noremap             <space>mn      :Marks<cr>
noremap             <space>al      :FZF! $HOME/zadania/Algos<cr>
noremap             <C-j>          <C-W>j
noremap             <C-k>          <C-W>k
noremap             <C-h>          <C-W>h
noremap             <C-l>          <C-W>l
let &t_SI .= "\e[6 q"  " Line cursor in insert mode
let &t_EI .= "\e[2 q"  " Block cursor in normal mode
let &t_SR .= "\e[4 q"  " replace mode
let g:fzf_history_dir = '~/.local/share/fzf-history'

set encoding=utf-8

set shiftwidth=4
set tabstop=4
set expandtab
let g:fzf_layout = { 'window': { 'width': 0.95 , 'height': 0.95 , 'relative':v:false} }
let g:fzf_preview_window = ['up:70%', 'ctrl-/']
