return {
	{
		"nvim-treesitter/nvim-treesitter",
		opts = {
			ensure_installed = {
				"asm",
				"bash",
				"c",
				"cmake",
				"cpp",
				"cuda",
				"editorconfig",
				"git_config",
				"gitcommit",
				"gitignore",
				"glsl",
				"go",
				"haskell",
				"html",
				"julia",
				"json",
				"llvm",
				"lua",
				"luadoc",
				"make",
				"markdown",
				"nasm",
				"nim",
				"nix",
				"ocaml",
				"ocaml_interface",
				"python",
				"rust",
				"toml",
				"vim",
				"vimdoc",
				"xml",
				"yaml",
			},
			auto_install = false,
			sync_install = false,

			highlight = {
				enable = true,
				disable = {},
				additional_vim_regex_highlighting = true,
			},
			indent = { enable = false, disable = {} },
		},
		config = function(_, opts)
			require("nvim-treesitter.configs").setup(opts)
		end,
	},
}
