return {
	{
		"nvim-treesitter/nvim-treesitter",
		-- version = "*",
		version = "v0.9.1",
		-- version = "v0.9.3",
		opts = {
			ensure_installed = {
				"asm",
				"bash",
				"c",
				"cmake",
				"comment",
				"commonlisp",
				"cpp",
				"cuda",
				"editorconfig",
				"editorconfig",
				"git_config",
				"git_rebase",
				"gitattributes",
				"gitcommit",
				"gitignore",
				"glsl",
				"go",
				"haskell",
				"html",
				"java",
				"json",
				"julia",
				"llvm",
				"lua",
				"luadoc",
				"luap",
				"luau",
				"make",
				"markdown",
				"nasm",
				"nim",
				"nix",
				"objdump",
				"ocaml",
				"ocaml_interface",
				"python",
				"rust",
				"strace",
				"toml",
				"vim",
				"vimdoc",
				"xml",
				"xresources",
				"yaml",
				"zig",
			},

			auto_install = false,
			sync_install = false,

			highlight = {
				additional_vim_regex_highlighting = false,
				custom_captures = {},
				-- disable = { "typst" },
				enable = true,
				loaded = false,
			},
			incremental_selection = {
				enable = false,
				-- disable = { "typst" },
				keymaps = {
					init_selection = "gnn",
					node_decremental = "grm",
					node_incremental = "grn",
					scope_incremental = "grc",
				},
			},
			indent = {
				-- disable = { "typst" },
				enable = false,
			},
		},
		config = function(_, opts)
			require("nvim-treesitter.configs").setup(opts)
		end,
	},
}
