return {
	{
		"nvim-treesitter/nvim-treesitter",
		opts = {
			ensure_installed = {
				"asm",
				"bash",
				"c",
				"cmake",
				"cpp",
				"cuda",
				"editorconfig",
				"git_config",
				"gitcommit",
				"gitignore",
				"glsl",
				"go",
				"haskell",
				"html",
				"java",
				"json",
				"julia",
				"llvm",
				"lua",
				"luadoc",
				"make",
				"markdown",
				"nasm",
				"nim",
				"nix",
				"ocaml",
				"ocaml_interface",
				"python",
				"rust",
				"toml",
				"vim",
				"vimdoc",
				"xml",
				"yaml",
				"zig",
			},
			auto_install = false,
			sync_install = false,

			highlight = {
				additional_vim_regex_highlighting = true,
				custom_captures = {},
				disable = {},
				enable = true,
				loaded = false,
			},
			incremental_selection = {
				enable = false,
				disable = {},
				keymaps = {
					init_selection = "gnn",
					node_decremental = "grm",
					node_incremental = "grn",
					scope_incremental = "grc",
				},
			},
			indent = {
				disable = {},
				enable = false,
			},
		},
		config = function(_, opts)
			require("nvim-treesitter.configs").setup(opts)
		end,
	},
}
