wget https://raw.githubusercontent.com/nim-lang/nim-mode/refs/heads/master/nim-vars.el
wget https://raw.githubusercontent.com/nim-lang/nim-mode/refs/heads/master/nim-util.el
wget https://raw.githubusercontent.com/nim-lang/nim-mode/refs/heads/master/nim-syntax.el
wget https://raw.githubusercontent.com/nim-lang/nim-mode/refs/heads/master/nim-suggest.el
wget https://raw.githubusercontent.com/nim-lang/nim-mode/refs/heads/master/nim-smie.el
wget https://raw.githubusercontent.com/nim-lang/nim-mode/refs/heads/master/nim-rx.el
wget https://raw.githubusercontent.com/nim-lang/nim-mode/refs/heads/master/nim-mode.el
wget https://raw.githubusercontent.com/nim-lang/nim-mode/refs/heads/master/nim-helper.el
wget https://raw.githubusercontent.com/nim-lang/nim-mode/refs/heads/master/nim-fill.el
wget https://raw.githubusercontent.com/nim-lang/nim-mode/refs/heads/master/nim-compile.el
wget https://raw.githubusercontent.com/nim-lang/nim-mode/refs/heads/master/nim-capf.el
